import numpy as np
a=np.array([1,3,4,5,9])
print("Array a :",a)
sum=np.sum(a)
print( "sum :",sum)
product=np.prod(a)
print("product :",product)
mean=np.mean(a)
print("mean :",mean)
standard_deviation=np.std(a)
print("standard_deviation:",standard_deviation)
variance=np.var(a)
print("variance :",variance)
minimum=np.min(a)
print("minimum value:",minimum )
maximum=np.max(a)
print("maximum value:",maximum)
minimum_index=np.argmin(a)
print("minimum index :",minimum_index)
maximum_index=np.argmax(a)
print("maximum_index:",maximum_index)
median=np.median(a)
print("median:",median)
prod=np.prod(a)
print("product :",prod)
print("Hello world")
print("Good Morning")